### ISSUE TITLE
Erro do modulo ao criar cliente pelo admin

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#100]
```
Please use the following template to submit your issue. 
Following this template will allow us to quickly investigate and help you with your issue. 
Please be aware that issues which do not conform to this template may be closed. 

DO NOT FORGET TO REMOVE THIS BLOCK
```

### Status

BUG REPORT / TASK

### Checklist

Add checklist if this is a task

### Steps

1. Crie uma conta de cliente pelo admim. 

### Expected behaviour

Conta do cliente criada 

How do you think the program should work? Add screenshots and code blocks if necessary.

### Actual behaviour

Erro e informação no log.

How does the program work in its current state?

### Environment

Magento versão 2.4.3-p2
PHP 7.4

You may write here the specifications like the version of the project, services, operating system, or hardware if applicable.

### Logs / Stack trace

[2022-07-12 17:42:25] main.CRITICAL: Error: Call to undefined method Exception::getResponseBody() in /usr/share/nginx/magentofiles/vendor/pagarme/pagarme-magento2-module/Observer/AdminCustomerBeforeSave.php:54
Stack trace:
#0 /usr/share/nginx/magentofiles/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Pagarme\Pagarme\Observer\AdminCustomerBeforeSave->execute()
#1 /usr/share/nginx/magentofiles/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#2 /usr/share/nginx/magentofiles/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#3 /usr/share/nginx/magentofiles/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#4 /usr/share/nginx/magentofiles/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php(349): Magento\Framework\Event\Manager\Proxy->dispatch()
#5 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Adminhtml\Index\Save->execute()
#6 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callParent()
#7 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}()
#8 /usr/share/nginx/magentofiles/generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php(23): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callPlugins()
#9 /usr/share/nginx/magentofiles/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->execute()
#10 /usr/share/nginx/magentofiles/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#11 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#12 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callParent()
#13 /usr/share/nginx/magentofiles/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}()
#14 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#15 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}()
#16 /usr/share/nginx/magentofiles/generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php(32): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callPlugins()
#17 /usr/share/nginx/magentofiles/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->dispatch()
#18 /usr/share/nginx/magentofiles/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#19 /usr/share/nginx/magentofiles/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#20 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#21 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#22 /usr/share/nginx/magentofiles/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#23 /usr/share/nginx/magentofiles/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#24 /usr/share/nginx/magentofiles/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#25 /usr/share/nginx/magentofiles/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#26 /usr/share/nginx/magentofiles/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#27 {main} [] []

```
Insert your log/stack trace here
```

**Comment by fabiano-mallmann** [comment]
@redati resolvemos alguns bugs referente a essa criação/alteração de usuários via admin. 
Você tem algum bug referente a isso?
