### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by heitorforner** [pagarme/magento2#104]
Support for the Magento 2.4.0-2.4.3 release line ends on November 28, 2022.

https://devdocs.magento.com/release/released-versions.html

### Status

TASK

### Checklist

- [_] PHP 8.1 Support with composer 2

### Steps

Upgrade from Magento 2.4.3 (PHP 7.4) to Magento 2.4.5 (PHP 8.1)

### Expected behaviour

Upgrade completed successfully

### Actual behaviour

Composer error: pagarme does not support PHP 8 and mundipagg is abandoned

### Environment

Magento 2.4.5 with PHP 8.1 (Redis 6, ElasticSearch 7.9)

**Comment by RafaMelazzo** [comment]
Hi @heitorforner and @douglaslessing!

We have support for PHP 8.1 since the release of version 2.0.4.

Thanks for the heads up! 😄
