### ISSUE TITLE
Pedido Cancelado erro estoque

### ISSUE THREAD

**Issue by awakebrasil** [pagarme/magento2#106]
Pedidos cancelados no cartão de crédito por falha de pagamento, anti-fraude ou saldo insuficiente, são cancelados mas os produtos do pedido não retornam para o estoque e continuam em reserva de estoque impedindo a venda. 

Estamos com um cliente com volume grande de vendas que está com o estoque completamente prejudicado devido a essa ação. 

Teriam ideia de alguma solução emergencial para o ajustes desse estoque? 

Obrigado

**Comment by RafaMelazzo** [comment]
Boa tarde @iurimedeiros! Tudo bem?

Está tendo problema com esse erro ainda? Caso precise de suporte, nos envie um e-mail para opensource@pagar.me com seu site e e-mail de cadastro na Pagar.me, para podermos investigar esse problema e corrigir o Plugin. Entraremos em contato em seguida.

Obrigado!
