### ISSUE TITLE
main.CRITICAL: TypeError: Argument 2 passed to Monolog

### ISSUE THREAD

**Issue by samuelmafra** [pagarme/magento2#108]
Erro acontece aleatoriamente, apresentando ao cliente no checkout: ERRO NO SERVIDOR,  ALGO DEU ERRADO NA SUA SOLICITACAO, SOMETHING WENT WRONG WITH YOUR REQUEST.

[2022-10-06 01:26:55] main.CRITICAL: TypeError: Argument 2 passed to Monolog\Logger::info() must be of the type array, null given, called in /home/customer/public_html/magento2/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/LogService.php on line 47 and defined in /home/customer/public_html/magento2/vendor/monolog/monolog/src/Monolog/Logger.php:640
Stack trace:
#0 /home/customer/public_html/magento2/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/LogService.php(47): Monolog\Logger->info('Order #10001177...', NULL)
#1 /home/customer/public_html/magento2/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderLogService.php(16): Pagarme\Core\Kernel\Services\LogService->info('Order #10001177...', Object(MundiAPILib\Models\CreateOrderRequest))
#2 /home/customer/public_html/magento2/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/APIService.php(149): Pagarme\Core\Kernel\Services\OrderLogService->orderInfo('100011779', 'Create order Re...', Object(MundiAPILib\Models\CreateOrderRequest))
#3 /home/customer/public_html/magento2/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php(265): Pagarme\Core\Kernel\Services\APIService->createOrder(Object(Pagarme\Core\Payment\Aggregates\Order))
#4 /home/customer/public_html/magento2/vendor/pagarme/pagarme-magento2-module/Gateway/Transaction/Base/Command/InitializeCommand.php(146): Pagarme\Core\Kernel\Services\OrderService->createOrderAtPagarme(Object(Pagarme\Pagarme\Concrete\Magento2PlatformOrderDecorator))
#5 /home/customer/public_html/magento2/vendor/pagarme/pagarme-magento2-module/Gateway/Transaction/Base/Command/InitializeCommand.php(50): Pagarme\Pagarme\Gateway\Transaction\Base\Command\InitializeCommand->doCoreDetour(Object(Magento\Sales\Model\Order\Payment\Interceptor))
#6 /home/customer/public_html/magento2/vendor/magento/module-payment/Model/Method/Adapter.php(549): Pagarme\Pagarme\Gateway\Transaction\Base\Command\InitializeCommand->execute(Array)
#7 /home/customer/public_html/magento2/vendor/magento/module-payment/Model/Method/Adapter.php(655): Magento\Payment\Model\Method\Adapter->executeCommand('initialize', Array)
#8 /home/customer/public_html/magento2/vendor/magento/module-sales/Model/Order/Payment.php(377): Magento\Payment\Model\Method\Adapter->initialize('authorize_captu...', Object(Magento\Framework\DataObject))
#9 /home/customer/public_html/magento2/vendor/magento/module-sales/Model/Order.php(992): Magento\Sales\Model\Order\Payment->place()
#10 /home/customer/public_html/magento2/vendor/magento/module-sales/Model/Order.php(1214): Magento\Sales\Model\Order->_placePayment()
#11 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
#12 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)
#13 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
#14 /home/customer/public_html/magento2/generated/code/Magento/Sales/Model/Order/Interceptor.php(32): Magento\Sales\Model\Order\Interceptor->___callPlugins('place', Array, Array)
#15 /home/customer/public_html/magento2/vendor/magento/module-sales/Model/Service/OrderService.php(209): Magento\Sales\Model\Order\Interceptor->place()
#16 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
#17 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent('place', Array)
#18 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#19 /home/customer/public_html/magento2/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(32): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, Array)
#20 /home/customer/public_html/magento2/vendor/magento/module-quote/Model/QuoteManagement.php(575): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
#21 /home/customer/public_html/magento2/vendor/magento/module-quote/Model/QuoteManagement.php(456): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#22 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#23 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('submit', Array)
#24 /home/customer/public_html/magento2/vendor/magento/module-sales-rule/Plugin/CouponUsagesIncrement.php(54): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#25 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\SalesRule\Plugin\CouponUsagesIncrement->aroundSubmit(Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Closure), Object(Magento\Quote\Model\Quote\Interceptor))
#26 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor))
#27 /home/customer/public_html/magento2/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(23): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('submit', Array, NULL)
#28 /home/customer/public_html/magento2/vendor/magento/module-quote/Model/QuoteManagement.php(414): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote\Interceptor))
#29 /home/customer/public_html/magento2/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(125): Magento\Quote\Model\QuoteManagement->placeOrder(282837)
#30 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(282837, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address))
#31 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#32 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(282837, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address))
#33 /home/customer/public_html/magento2/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
#34 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(282837, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address))
#35 /home/customer/public_html/magento2/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#36 /home/customer/public_html/magento2/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#37 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#39 /home/customer/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /home/customer/public_html/magento2/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#41 /home/customer/public_html/magento2/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /home/customer/public_html/magento2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#43 /home/customer/public_html/magento2/pub/index.php(47): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by samuelmafra** [comment]
Bom dia, esse erro tinha relação as mudanças do seguinte commit:

https://github.com/pagarme/ecommerce-module-core/commit/80578e75ccabb520b41f4aec698e87722b4af07e

O commit de 19 de setembro reverteu essa mudança e o problema desapareceu.

**Comment by RafaMelazzo** [comment]
Obrigado por reportar @samuelmafra!
