### ISSUE TITLE
Erro ao Cancelar Pedido

### ISSUE THREAD

**Issue by iurimedeiros** [pagarme/magento2#114]
Ao clicar para cancelar algum pedido pendente no Magento 2.4.3 retorna a seguinte mensagem: Você não cancelou o item.

O problema de manter pedidos com status de Pendente é de que o Magento acaba criando uma reserva de estoque, dessa forma acaba impactando nas vendas pois os clientes posteriores não conseguem finalizar a compra devido a mensagem de erro: A quantidade solicitada não está disponível.

**Comment by RafaMelazzo** [comment]
Boa tarde @iurimedeiros! Tudo bem?

Está tendo esse erro no seu site ainda? Caso precise de suporte ainda, nos envie um e-mail para [opensource@pagar.me](mailto:opensource@pagar.me) com seu site e e-mail de cadastro na Pagar.me, para podermos investigar esse problema e corrigir o Plugin. Entraremos em contato em seguida.

Obrigado!
