### ISSUE TITLE
Failed to load the "Pagarme_Pagarme/js/view/payment/creditcard" component.

### ISSUE THREAD

**Issue by nelsonbf** [pagarme/magento2#144]
### Status

BUG REPORT 

### Checklist

Add checklist if this is a task

- [x] Support xyz 

### Steps

1. Conectar dashboard Pagar.me
2. Tentar acessar o checkout e visualizer as formas de pagamento Pagar.me

### Expected behaviour

Visualizar formas de pagamento no checkout

### Actual behaviour

Formas de pagamento não aparecem no checkout, mesmo tendo liberado o domínio no painel do pagar.me. Erros abaixo vistos no console:

[2023-02-06 09:24:32] [ERROR] Failed to load the "Pagarme_Pagarme/js/view/payment/creditcard" component.

VM32627:4 [2023-02-06 09:24:32] [ERROR] Failed to load the "Pagarme_Pagarme/js/view/payment/pix" component.

VM32627:4 [2023-02-06 09:24:32] [ERROR] Failed to load the "Pagarme_Pagarme/js/view/payment/boleto" component.

### Environment

M2 2.4.5

**Comment by Marusso** [comment]
@nelsonbf tive esse mesmo problema, única forma de "resolver" que encontrei foi desabilitando a opção do magento de minificar arquivos javascript e mesclar arquivos javascript.

Seria interessante o pessoal da Pagar.me ajustar esse erro para poder utilizar a função de mesclar arquivos de js do magento novamente.

**Comment by RafaMelazzo** [comment]
Olá @nelsonbf e @Marusso! Tudo bem?

Vamos adicionar em nossa esteira de desenvolvimento e assim que possível lhe damos um retorno aqui.

Obrigado! 😄

**Comment by mateus-picoloto** [comment]
Olá @nelsonbf e @Marusso, tudo bem?

Fizemos compatibilização com a minificação e bundle de javascript na versão 2.2.5 do módulo. Caso o problema ainda persista, favor reabir a issue.

Muito obrigado!
