### ISSUE TITLE
UPDATE database em todas as requisições na loja que não faz sentido

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#152]
```
Notei com ferramenta de debug que em todos os acessos um update desnecessário é feito. Devido ao observer.

Então eu desativei eles. Isso parece um comportamento estranho.

magento 2.4.5-p1 php8.1, modulo 2.0.6

este osberver também gera outro erro 
main.CRITICAL: Exception: Warning: foreach() argument must be of type array|object, null given in Pagarme/Pagarme/Observer/DiscountCyclesObserver.php on line 55

eu apenas deixo comentado e tudo funciona bem
<!-- event name="catalog_controller_product_view">
        <observer name="update_product_cycle_value"
                  instance="Pagarme\Pagarme\Observer\DiscountCyclesObserver" />
    </event -->

```
![Captura de tela 2023-03-09 133245](https://user-images.githubusercontent.com/6043222/224090103-65c75018-1377-47c4-bc89-c3ac306ca41f.jpg)
![Captura de tela 2023-03-09 133108](https://user-images.githubusercontent.com/6043222/224090113-f76f230a-de66-486c-886a-606e58b957f9.jpg)

### Status

BUG REPORT / TASK

### Checklist

Add checklist if this is a task

- [x] Add slack integration
- [_] Support xyz 

### Steps

1. First step
2. Second step
3. Third step

### Expected behaviour

How do you think the program should work? Add screenshots and code blocks if necessary.

### Actual behaviour

How does the program work in its current state?

### Environment

You may write here the specifications like the version of the project, services, operating system, or hardware if applicable.

### Logs / Stack trace

```
Insert your log/stack trace here
```

**Comment by fabiano-mallmann** [comment]
@redati vamos adicionar em nossa esteira de desenvolvimento e assim que possível lhe damos um retorno aqui.

**Comment by RafaMelazzo** [comment]
Olá @redati! Tudo bem?

Essa correção foi efetuada e está em testes no momento. Será publicada na próxima versão.

Assim que lançada eu retorno aqui para te avisar novamente.

Muito obrigado! 😄

**Comment by mateus-picoloto** [comment]
Olá @redati, tudo bem?

Essa correção foi lançada na versão 2.2.5.

Muito obrigado!
