### ISSUE TITLE
Pagamento aprovado na Pagarme e pedido não entra na Magento

### ISSUE THREAD

**Issue by samuelmafra** [pagarme/magento2#168]
Boa tarde,

Esse erro vem ocorrendo aleatoriamente já algum tempo, clientes digitam os dados do cartão e tentam finalizar a compra.

Nos logs aparece: Webhook.ERROR: Order not found: or_2EqX59KTzRFRXXx

Porém a transação foi autorizada pela Pagarme, e o pedido não é registrado na Magento.

Versão Magento 2.4.3 CE

**Comment by samuelmafra** [comment]
Bom dia,

Erro persistindo a versão Magento 2.4.5-p2.

"moduleVersion": "2.2.1"
"coreVersion": "2.2.0"

[2023-04-30 10:24:59] Webhook.ERROR: Order not found: or_brAQKNeTE3uNbxxx | Exception code: 404
Version: m: 2.2.1 c: 2.2.0 p: Magento Community 2.4.5-p2 
From: /home/account/public_html/magento2/vendor/pagarme/pagarme-magento2-module/Model/WebhookManagement.php:42 -> Pagarme\Core\Webhook\Services\WebhookReceiverService::handle
{
    "type": "Pagarme\\Core\\Kernel\\Exceptions\\NotFoundException",
    "code": 404,
    "message": "Order not found: or_brAQKNeTE3uNbx1k",
    "file": "\/home\/account\/public_html\/magento2\/vendor\/pagarme\/ecommerce-module-core\/src\/Kernel\/Factories\/OrderFactory.php",
    "line": 142,
    "trace": "#0 \/home\/account\/public_html\/magento2\/vendor\/pagarme\/ecommerce-module-core\/src\/Webhook\/Services\/ChargeOrderService.php(427): Pagarme\\Core\\Kernel\\Factories\\OrderFactory->createFromPlatformData(Object(Pagarme\\Pagarme\\Concrete\\Magento2PlatformOrderDecorator), 'or_brAQKNeTE3uN...')\n#1 \/home\/account\/public_html\/magento2\/vendor\/pagarme\/ecommerce-module-core\/src\/Webhook\/Services\/AbstractHandlerService.php(55): Pagarme\\Core\\Webhook\\Services\\ChargeOrderService->loadOrder(Object(Pagarme\\Core\\Webhook\\Aggregates\\Webhook))\n#2 \/home\/account\/public_html\/magento2\/vendor\/pagarme\/ecommerce-module-core\/src\/Webhook\/Services\/ChargeHandlerService.php(56): Pagarme\\Core\\Webhook\\Services\\AbstractHandlerService->handle(Object(Pagarme\\Core\\Webhook\\Aggregates\\Webhook))\n#3 \/home\/account\/public_html\/magento2\/vendor\/pagarme\/ecommerce-module-core\/src\/Webhook\/Services\/WebhookReceiverService.php(44): Pagarme\\Core\\Webhook\\Services\\ChargeHandlerService->handle(Object(Pagarme\\Core\\Webhook\\Aggregates\\Webhook))\n#4 \/home\/account\/public_html\/magento2\/vendor\/pagarme\/pagarme-magento2-module\/Model\/WebhookManagement.php(42): Pagarme\\Core\\Webhook\\Services\\WebhookReceiverService->handle(Object(stdClass))\n#5 [internal function]: Pagarme\\Pagarme\\Model\\WebhookManagement->save('hook_AXlN6ehD6I...', 'charge.paid', Array)\n#6 \/home\/account\/public_html\/magento2\/vendor\/magento\/module-webapi\/Controller\/Rest\/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#7 \/home\/account\/public_html\/magento2\/vendor\/magento\/module-webapi\/Controller\/Rest.php(195): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#8 \/home\/account\/public_html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/home\/account\/public_html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#10 \/home\/account\/public_html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/home\/account\/public_html\/magento2\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#12 \/home\/account\/public_html\/magento2\/vendor\/magento\/framework\/App\/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#13 \/home\/account\/public_html\/magento2\/vendor\/magento\/framework\/App\/Bootstrap.php(264): Magento\\Framework\\App\\Http->launch()\n#14 \/home\/account\/public_html\/magento2\/pub\/index.php(75): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#15 {main}"
}
[2023-04-30 10:26:12] Order.INFO: Order #1000148XXX : Quote already used, order id duplicated. Customer Note: pagarme-processing
Version: m: 2.2.1 c: 2.2.0 p: Magento Community 2.4.5-p2 
From: /home/account/public_html/magento2/vendor/pagarme/pagarme-magento2-module/Gateway/Transaction/Base/Command/InitializeCommand.php:51 -> Pagarme\Pagarme\Gateway\Transaction\Base\Command\InitializeCommand::doCoreDetour
[]
[2023-04-30 10:26:12] Order.INFO: Order #1000148XXX : Order failed, changing status quote to failed. 
Error message: Quote already used, order id duplicated.
Version: m: 2.2.1 c: 2.2.0 p: Magento Community 2.4.5-p2 
From: /home/account/public_html/magento2/vendor/pagarme/pagarme-magento2-module/Gateway/Transaction/Base/Command/InitializeCommand.php:51 -> Pagarme\Pagarme\Gateway\Transaction\Base\Command\InitializeCommand::doCoreDetour
[]

**Comment by redati** [comment]
você usa replicação de banco de dados?

**Comment by samuelmafra** [comment]
> você usa replicação de banco de dados

Não.

**Comment by redati** [comment]
algum campo null esta dando problema na linha https://github.com/pagarme/ecommerce-module-core/blob/cec3f0e0f4bfd51418d1038ddeec29ad0d921f31/src/Kernel/Log/BlurData.php#L34 

pode ver que a função requer uma string e não aceita null:
private function blurStringSensitiveData(string $value, $delimiter)

vai precisar localizar esse campo nullo em que o módulo espera que seja uma string (algum campo do checkout).

usa algum modulo de terceiro para checkout? essa função apenas evita que informçaões sensíveis sejam envaidas para log. Eu nunca tive esse problema, já usei esta versão, agora atualizei para 2.4.6. 

Se o erro acontece ocasionalmente, isso é devido ao processo de compra, algum dos procesos estão falhando, por exemplo, se um cliente já tem endereço cadastrado e o endereço tem algum campo destualizado e esse cliente específico tem problemas. Também se o cliente cadastra endereços diferentes e o modulo de checkout não atualiza corretamente os dados do pedido. 
Eu uso o modulo do Elisei, o melhor que já vi para o magento https://github.com/elisei/full-checkout e não tenho problemas.

**Comment by samuelmafra** [comment]
Nenhum módulo terceiro para checkout, porém temos o m2-systemcode/BrazilCustomerAttributes que possui observer no checkout.

O erro acontece de forma aleatória (poucas vezes), tanto para clientes novos como para clientes já existentes.

**Comment by RafaMelazzo** [comment]
Boa tarde @samuelmafra! Tudo bem?

Está tendo esse erro no seu site ainda? Caso precise ainda, nos envie um e-mail para opensource@pagar.me com seu site e e-mail de cadastro na Pagar.me, para podermos investigar esse problema e corrigir o Plugin. Entraremos em contato em seguida.

Obrigado!

**Comment by samuelmafra** [comment]
Boa tarde,

Sim, o erro acontece de vez enquanto, inclusive no pagamento por PIX (até a abertura dessa issue só acontecia no cartão de crédito).

Vou encaminhar e-mail.

Obrigado.

**Comment by robsoned** [comment]
Boa tarde, debugando aqui, como @redati comentou , `private function blurStringSensitiveData(string $value, $delimiter)`, não aceita `null`, porém, já que se trata de uma função de tratar dados sensível, antes de escrever em um arquivo de log. Acredito que essa função poderia ser alterada para o parâmetro ser opicional, pois se estamos falando de dados sensíveis, não deveria ser obrigatório e interromper o fluxo da compra, gerando inconsistência entre as plataformas.

#

Minha sugestão seria alterar a declaração do método para:

`private function blurStringSensitiveData(string $value = "", $delimiter)`.

#

Porém, acho que podemos ir além. O método `logService->orderInfo()` é chamado diversas vezes, dentro do código em [pagarme/ecommerce-module-core](https://github.com/pagarme/ecommerce-module-core) fora de blocos `try catch`. 

No exemplo abaixo, no arquivo `src/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderCreationService.php(81)`. Na linha 81, o código está tentando logar `$response`, que é o retorno da própria API da pagarme, não do magento.

![image](https://github.com/pagarme/magento2/assets/18008565/d75671cd-4433-4a4a-89be-2dfb6920636d)

#

Para resolver essa questão, poderia ser adicionado um bloco `try catch` nos métodos que fazem a escrita para os arquivos de logs, pois podem ocorrer vários erros nesse processo de logar os dados para um arquivo, disco cheio, permissão de usuário e etc. 

![image](https://github.com/pagarme/magento2/assets/18008565/8bd5290c-69c4-4a38-9e3a-dd0dc115a9a4)

#

Criei uma PR la em [ecommerce-module-core](https://github.com/pagarme/ecommerce-module-core), com as alterações mencionadas acima.

https://github.com/pagarme/ecommerce-module-core/pull/107

**Comment by mateus-picoloto** [comment]
Olá @samuelmafra, tudo bem?

A correção que o @robsoned abriu para o [ecommerce-module-core](https://github.com/pagarme/ecommerce-module-core) já foi lançada na versão 2.2.3. Com a versão mais recente do nosso módulo você ainda está tendo esse problema?

**Comment by RafaMelazzo** [comment]
Bom dia @samuelmafra! Tudo bem?

Estou fechando essa issue por falta de resposta. Caso ainda tenha algum problema, pode abrir outra issue ou entre em contato com a gente através do e-mail opensource@pagar.me.

Obrigado!
