### ISSUE TITLE
Deprecated Functionality: Creation of dynamic property Pagarme\Pagarme\Console\MigrateData::$connection is deprecated in /var/www/html/app/code/Pagarme/Pagarme/Console/MigrateData.php on line 19

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#171]
PHP 8.2 Magento 2.4.6

Aqui basta criar antes a variável "private $connection, $start;"

Deprecated Functionality: Creation of dynamic property Pagarme\Pagarme\Console\MigrateData::$connection is deprecated in /var/www/html/app/code/Pagarme/Pagarme/Console/MigrateData.php on line 19

esse erro ocorre em muitas partes do modulo.

**Comment by betocamin** [comment]
> Olá @redati! Tudo bem?
> 
> Essas correções foram efetuadas e estão em teste no momento, junto de outras alterações, e serão lançadas na próxima versão.
> 
> Assim que lançada eu retorno aqui para te avisar.
> 
> Muito obrigado! 😄

Tem previsão lançamento da versão compatível com 2.4.6?

**Comment by RafaMelazzo** [comment]
Olá @betocamin!

O lançamento deve ocorrer no início do mês que vem. Ela já está disponível em versão de desenvolvimento, na branch **stg**. Caso queira, pode baixá-la com o seguinte comando:

`composer require pagarme/pagarme-magento2-module:dev-stg`

**Comment by perrera** [comment]
Já tem o release que corrige esse erro??
