### ISSUE TITLE
Tratamento incorreto de verificação de cpf

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#181]
Para php 8.1+ os tipos vão da erro, pois o campo é nulo se o logista usa cpf do endereço. Essa verificação precisa de um pequeno ajuste 

$customerDocument = $this->cleanCustomerDocument(
            $quote->getCustomer()->getTaxVat()
        )

https://github.com/pagarme/magento2/blob/58811e6de5c24683fc842060a95e38ab08803c7c/Concrete/Magento2PlatformOrderDecorator.php#L544

isso aqui resolveu temporariamente pra mim.

$doc = (String) $quote->getCustomer()->getTaxVat() != null ? $quote->getCustomer()->getTaxVat() : '';

        $customerDocument = $this->cleanCustomerDocument(
            $doc
        );

![Sem Título-1](https://user-images.githubusercontent.com/6043222/232845302-c54938b1-c5e9-467a-8aa2-d3d9a4c247e1.jpg)

**Comment by redati** [comment]
erro após esse commit https://github.com/pagarme/magento2/commit/67982d934cc93abdf4f4e07c0a0995b1464e3386

**Comment by fabiano-mallmann** [comment]
@redati Muito obrigado pela colaboração!
