### ISSUE TITLE
Colocar icone de copiar pix dentro do link e ajustar css responsivo

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#191]
Olá. Encontrei alguns cliente tentando copiar o código pix clicando no icone, e não clicaram no link, depois saíram da página sem efetuar o pagamento. Para melhorar a usabilidade, deixo aqui a sugestão para incluír o icone no link.

![Captura de tela 2023-05-04 170512](https://user-images.githubusercontent.com/6043222/236317476-f11b682c-71da-4a31-af13-d35f8375478c.jpg)

**Comment by redati** [comment]
https://github.com/pagarme/magento2/blob/7ff4068d3faf6d36692dbd00bbb145e37b6a5bcb/view/frontend/templates/payment/pix.phtml#L6 style com 420px de largura, sendo que os dispositivos menores, em usa maioria é 360px.

**Comment by mateus-picoloto** [comment]
Olá @redati, tudo bem?

Essa correção foi lançada na versão 2.2.5.

Muito obrigado!
