### ISSUE TITLE
The specified HTTP code "0" is invalid

### ISSUE THREAD

**Issue by robsoned** [pagarme/magento2#237]
Olá, encontrei um erro que está acontecendo no módulo, quando Base/Command/InitializeCommand.php, no  método `doCoreDetour`, tenta instanciar uma nova classe <b>Magento\Framework\Webapi\Exception</b>

#

Segue o log:

    
    main.CRITICAL: InvalidArgumentException: The specified HTTP code "0" is invalid. in /var/www/html/vendor/magento/framework/Webapi/Exception.php:111

    /var/www/html/vendor/pagarme/pagarme-magento2-module/Gateway/Transaction/Base/Command/InitializeCommand.php(169): Magento\Framework\Webapi\Exception->__construct()

#
    
Ao analisar `pagarme/pagarme-magento2-module/Gateway/Transaction/Base/Command/InitializeCommand.php` . 

https://github.com/pagarme/magento2/blob/6b104b4cdb398bce7c4d6bc8786ba3c9491cd8e7/Gateway/Transaction/Base/Command/InitializeCommand.php#L32

https://github.com/pagarme/magento2/blob/6b104b4cdb398bce7c4d6bc8786ba3c9491cd8e7/Gateway/Transaction/Base/Command/InitializeCommand.php#L154-L171

Podemos ver que está passando `$e->getCode` no terceiro parametro do construtor da classe `Magento\Framework\Webapi\Exception as M2WebApiException`, na linha 169.

#

O método `getCode` da classe `\Exception` nem sempre irá retornar um valor entre `400` e `599`, conforme a validação feita no construtor da classe `Magento\Framework\Webapi\Exception `. Causando o erro descrito no log. 

https://github.com/magento/magento2/blob/0b16f58cfab816da886b700c36ec177a66a829e9/lib/internal/Magento/Framework/Webapi/Exception.php#L97-L109
![image](https://github.com/pagarme/magento2/assets/18008565/750d3d08-106f-44b3-98d7-3fc30ae8eb65)

**Comment by mateus-picoloto** [comment]
Olá @robsoned, tudo bem?

Muito obrigado por ter reportado o bug e já aberto o PR com a correção! Irei fechar a issue, pois a correção já subiu na versão 2.2.5 do módulo
