### ISSUE TITLE
após atualizar para 2.2.5 - erro main.CRITICAL: Placing an order with quote_id 76950 is failed: Quote already used, order id duplicated. [] []

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#262]
Atualizei o modulo e agora recebo o erro. 
main.CRITICAL: Placing an order with quote_id 76950 is failed: Quote already used, order id duplicated. [] []

**Comment by RafaMelazzo** [comment]
Boa tarde @redati! Tudo bem?

Poderia nos enviar um e-mail para opensource@pagar.me com a URL do seu site e as informações da sua conta na Pagar.me para que a gente possa analisar esse erro?

Obrigado!

**Comment by redati** [comment]
boa tarde. enviado.
________________________________
De: Rafael Seiffer Melazzo ***@***.***>
Enviado: segunda-feira, 16 de outubro de 2023 16:20
Para: pagarme/magento2 ***@***.***>
Cc: Misael Gomes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pagarme/magento2] após atualizar para 2.2.5 - erro main.CRITICAL: Placing an order with quote_id 76950 is failed: Quote already used, order id duplicated. [] [] (Issue #262)


Boa tarde @redati<https://github.com/redati>! Tudo bem?

Poderia nos enviar um e-mail para ***@***.******@***.***> com a URL do seu site e as informações da sua conta na Pagar.me para que a gente possa analisar esse erro?

Obrigado!
