### ISSUE TITLE
Erro de Sintaxe  - pagarme/pagarme-magento2-module/Model/Notifications.php

### ISSUE THREAD

**Issue by ham1lts** [pagarme/magento2#309]
Nova versão do módulo esta com erro de sintaxe.

### Status

BUG REPORT

### Checklist

Add checklist if this is a task

### Steps

1. Instalar Módulo
2. Compilar código (`bin/magento setup:di:compile`)

### Expected behaviour

Compilação do código.

### Actual behaviour

Erro de Sintaxe.

### Environment

Versão do Módulo 2.4.
Versão Magento 2.3

### Logs / Stack trace

```
Parse error: syntax error, unexpected ')' in /var/www/html/vendor/pagarme/pagarme-magento2-module/Model/Notifications.php on line 216
```
![image](https://github.com/pagarme/magento2/assets/88402038/5c85d935-024a-481e-b62b-437a3f829ca2)

**Comment by mateus-picoloto** [comment]
Olá @ham1lts, tudo bem?

Criei um [PR com a correção](https://github.com/pagarme/magento2/pull/310) e ele será publicado na próxima versão do módulo. Assim que publicado a nova versão iremos vir aqui para te avisar.

Caso queira, na próxima vez que identificar um problema/nova funcionalidade e já tiver a implementação pode criar um PR aqui no repositório que iremos revisar e aprovar.

Muito obrigado!

**Comment by ham1lts** [comment]
Show de bola! 
Até mais!

**Comment by mateus-picoloto** [comment]
@ham1lts  a correção está em produção na versão 2.4.1.
