### ISSUE TITLE
cdn.mundipagg.com AuthorizationFailure

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#312]
algumas imagens do modulo que busca pela cdn da mundpagg, vem dando erro e não carrega no checkout,
não seria melhor pegar as imagens do proprio modulo?

https://cdn.mundipagg.com/assets/images/site/illustrations/pix-bc-logo-2.png

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AuthorizationFailure</Code>
<Message>This request is not authorized to perform this operation. RequestId:dad6606d-001e-0016-23ef-6b8d44000000 Time:2024-03-01T15:48:52.5602208Z</Message>
</Error>

**Comment by redati** [comment]
![Captura de tela 2024-03-01 130405](https://github.com/pagarme/magento2/assets/6043222/561b430b-3717-45b1-a59b-a3e10df6e129)

**Comment by redati** [comment]
outro erro de cors
![erro cors](https://github.com/pagarme/magento2/assets/6043222/9c013da3-b658-4103-9ffb-2cd4bc687de1)

**Comment by redati** [comment]
@RafaMelazzo

**Comment by mateus-picoloto** [comment]
Olá @redati, tudo bem?

Sobre o problema da logo já abrimos um [PR ](https://github.com/pagarme/magento2/pull/315) para corrigir. Assim que lançado uma versão com a correção avisamos aqui.

Já sobre o problema do CORS para a api de tokens, é necessário cadastrar o seu domínio na dash da pagar.me em Configurações -> Conta. Se mesmo cadastrando lá o problema ainda persistir poderia nos enviar um e-mail para opensource@pagar.me detalhando mais o problema.

Muito obrigado!

**Comment by redati** [comment]
Perfito, obrigado.

**Comment by mateus-picoloto** [comment]
@redati ainda não lançamos uma tag com a correção ainda, mas caso queira já aplicar a correção na tua loja é só rodar os comandos abaixo:

```
composer config minimum-stability dev
```
```
composer require pagarme/pagarme-magento2-module:dev-release/2.4.1
```

**Comment by mateus-picoloto** [comment]
@redati a correção está em produção na versão 2.4.1.
