### ISSUE TITLE
opção desatilitar carteira de cartões no admin, não reflete no frontend.

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#313]
A opção no checkout:
Tentei desabilitar na opção "habilitar carteira de cartão: não" mas não funciona. apenas escondi via css, "display: none".

**Comment by mateus-picoloto** [comment]
Olá @redati, tudo bem?

Então eu tentei simular o problema e não consegui. Abaixo segue um vídeo da tentativa:

https://github.com/pagarme/magento2/assets/38541352/3d89e1c8-ebb1-4ca3-88d6-049ae1b60fba

Poderia nos enviar um e-mail para [opensource@pagar.me](mailto:opensource@pagar.me) detalhando mais o problema e com evidencias.

Muito obrigado!

**Comment by redati** [comment]
vou tentar ver mais informações sobre o porque ainda aparece, obrigado pelo retorno.

**Comment by mateus-picoloto** [comment]
Olá @guiserinoli, tudo bem?

Muito obrigado por ter achado o ponto com problema, abri um [PR](https://github.com/pagarme/magento2/pull/316) com essa correção. Assim que lançado uma versão com a correção avisamos aqui.

**Comment by fabiano-mallmann** [comment]
Bom dia pessoal!
A correção está em produção na versão 2.4.1.
