### ISSUE TITLE
Problema ao preencher o numero do cartão

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#364]
Executo o processo de compra normal, no momento de digitar o cartão, ao digitar os primeiros 5 digitos, tudo apaga, encontrei o problema nas gravações do hotjar e consegui reproduzir fácilmente, usando ultima versão do magento e do módulo.

**Comment by redati** [comment]
no console, da o erro:
The specified value "1111 1" cannot be parsed, or is out of range.

porque eu tentei digitar 1111 e ao digitar o próximo 1, apagou tudo e deu o erro.

**Comment by redati** [comment]
parece que jquery mask tem alguns problemas com input type number com esstipo de mascara com espaço, mudei para input type text e resolveu por enquanto

**Comment by redati** [comment]
@fabiano-mallmann tudo bom? sebe me dizer se a solução é segura, porque mudando pra tipo texto, e não sei se o campo é trtado em algum lugar para remover os espaços.

**Comment by fabiano-mallmann** [comment]
@redati Pode me detalhar um pouco esse problema que ocorreu?

**Comment by redati** [comment]
desculpe, esta resolvido, na verdade eu tinha este aquivo modificado no tema e estava desatualizado /Pagarme_Pagarme/web/template/payment/creditcard-form.html 
tenho ele modificado porque desativei uso de cartão salvo mas continuava aparecendo campo para selecionar cartão salvo, então havia forçado a remoção deste campo e esqueci de atualizar o arquivo quando o modulo atualizou.

**Comment by fabiano-mallmann** [comment]
Beleza, qualquer coisa estamos à disposição.
