### ISSUE TITLE
Erro no retorno de pedidos por recorrência

### ISSUE THREAD

**Issue by awakebrasil** [pagarme/magento2#83]
Olá, 

Estamos enfrentando um problema com a recorrência, a loja virtual não recebe nenhuma notificação e renovação mesmo elas ocorrendo normalmente na pagar.me o que inviabiliza e dificulta muito a gestão das assinaturas. 

Poderiam me direcionar se existe algo a mais que precisa ser feito na recorrência, alguma configuração ou retorno da API? Já que as vendas avulsas funcionam perfeitamente. 

Analisando as funções do módulo me parece que forma correta é ele criar um pedido com o ID XXXX-2 depois XXXXX-3 vinculados ao pedido inicial. 

Aguardo retorno, obrigado.

**Comment by dias-joao** [comment]
Boa tarde @awakebrasil !

Por favor, entre em contato diretamente conosco através de nossos canais de atendimento disponível em: [Atendimento Pagar.me](https://docs.pagar.me/docs/overview-principal#atendimento)
