### ISSUE TITLE
Magento 2.4.4

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#84]
```
Please use the following template to submit your issue. 
Following this template will allow us to quickly investigate and help you with your issue. 
Please be aware that issues which do not conform to this template may be closed. 

DO NOT FORGET TO REMOVE THIS BLOCK
```

### Status

BUG REPORT
### Checklist

Add checklist if this is a task

- [_] Add slack integration
- [_] Support xyz 

### Steps

1. Upgrade Magento 2.4.4 Composer.
2. Install Module PagarMe: composer require pagarme/pagarme-magento2-module -W

### Expected behaviour

Upgrade and Install.

### Actual behaviour

Error dependencies. 

### Environment

Magento 3.4.3 to Magento 2.4.4

### Logs / Stack trace

Problem: 
    "monolog/monolog": "~1.6",
https://github.com/pagarme/ecommerce-module-core/blob/6784424e25bb790baa77065630f252f2e1d30a74/composer.json#L14

```
 Problem 1
    - pagarme/pagarme-magento2-module 1.1.1 requires pagarme/ecommerce-module-core 1.1.1 -> satisfiable by pagarme/ecommerce-module-core[1.1.1].
    - Conclusion: don't install pagarme/ecommerce-module-core 1.1.1 (conflict analysis result)
    - pagarme/pagarme-magento2-module[1.1.2, ..., 1.1.5] require pagarme/ecommerce-module-core 1.1.2 -> satisfiable by pagarme/ecommerce-module-core[1.1.2].
    - Conclusion: don't install pagarme/ecommerce-module-core 1.1.2 (conflict analysis result)
    - magento/magento2-functional-testing-framework is locked to version 3.8.0 and an update of this package was not requested.
    - Conclusion: don't install monolog/monolog 2.3.2 (conflict analysis result)
    - Conclusion: don't install monolog/monolog 1.26.0 (conflict analysis result)
    - Conclusion: don't install monolog/monolog 2.3.3 (conflict analysis result)
    - Conclusion: don't install monolog/monolog[1.26.1] | install one of monolog/monolog[2.3.4, 2.3.5, 2.4.0, 2.5.0] (conflict analysis result)
    - Conclusion: don't install monolog/monolog 2.3.4 (conflict analysis result)
    - Conclusion: don't install monolog/monolog 2.3.5 (conflict analysis result)
    - Conclusion: don't install monolog/monolog 2.4.0 (conflict analysis result)
    - Conclusion: don't install monolog/monolog 1.27.0 (conflict analysis result)
    - Conclusion: don't install monolog/monolog 2.5.0 (conflict analysis result)
    - pagarme/pagarme-magento2-module 1.1.0 requires pagarme/ecommerce-module-core 1.1.0 -> satisfiable by pagarme/ecommerce-module-core[1.1.0].
    - Root composer.json requires pagarme/pagarme-magento2-module ^1.1 -> satisfiable by pagarme/pagarme-magento2-module[1.1.0, ..., 1.1.5].
    - magento/product-community-edition is locked to version 2.4.4 and an update of this package was not requested.
    - pagarme/ecommerce-module-core 1.1.0 requires monolog/monolog ~1.6 -> satisfiable by monolog/monolog[1.6.0, ..., 1.27.0].
    - You can only install one version of a package, so only one of these can be installed: monolog/monolog[1.6.0, ..., 1.27.0, 2.3.0, ..., 2.5.0].
    - magento/product-community-edition 2.4.4 requires monolog/monolog ^2.3 -> satisfiable by monolog/monolog[2.3.0, ..., 2.5.0].
    - Conclusion: don't install monolog/monolog 2.3.1 (conflict analysis result)
```

**Comment by redati** [comment]
Precisamos atualizar para  monolog/monolog ^2.3

src/Kernel/Log/JsonPrettyFormatter.php apenas adicionar :String para ficar compatível com a versão atual e tudo parece ok.

    public function format(array $record) :String

**Comment by dias-joao** [comment]
@redati Bom dia!

Obrigado por suas observações! Iremos realizar as alterações, testar nas diversas versões e em breve liberar num release futuro.

At.te,

João Paulo

**Comment by corpsysgit** [comment]
> atualizar para monolog/monolog ^2.3
> 
> src/Kernel/Log/JsonPrettyFormatter.php apenas adicionar :String para ficar compatível com a versão atual e tudo parece ok.
> 
> ```
> public function format(array $record) :String
> ```

nao encontrei este caminho do arquivo.

**Comment by redati** [comment]
> > atualizar para monolog/monolog ^2.3
> > src/Kernel/Log/JsonPrettyFormatter.php apenas adicionar :String para ficar compatível com a versão atual e tudo parece ok.
> > ```
> > public function format(array $record) :String
> > ```
> 
> nao encontrei este caminho do arquivo.



NO CASO ISSO ESTA NA BIBLIOTECA PRINCIPAL DO MODULO  pagarme/ecommerce-module-core https://github.com/pagarme/ecommerce-module-core

COMO LA É FECHADO PARA RECEBER ISSUE. ENVIEI AQUI.
