### ISSUE TITLE
"pagarme/ecommerce-module-core": "1.1.2" não deveria ser "pagarme/ecommerce-module-core": "^1.1.2" ? Erro instalação 2.4.4

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#89]
https://github.com/pagarme/magento2/blob/a2f0e47085cc7feeda5a16937e417a9bef26b045/composer.json#L10

A instrução "pagarme/ecommerce-module-core": "1.1.2" no composer.json não permite que o modulo core seja baixado na sua ultima versão, assim compatível com magento 2.4.4. 

Ao instalar o modulo tenho o erro 
Problem 1
    - Root composer.json requires pagarme/ecommerce-module-core ^1.1 -> satisfiable by pagarme/ecommerce-module-core[1.1.2].
    - pagarme/ecommerce-module-core 1.1.2 requires monolog/monolog ~1.6 -> found monolog/monolog[1.6.0, ..., 1.27.0] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - pagarme/ecommerce-module-core 1.1.2 requires monolog/monolog ~1.6 -> found monolog/monolog[1.6.0, ..., 1.27.0] but these were not loaded, likely because it conflicts with another require.
    - pagarme/pagarme-magento2-module 1.1.5 requires pagarme/ecommerce-module-core 1.1.2 -> satisfiable by pagarme/ecommerce-module-core[1.1.2].
    - Root composer.json requires pagarme/pagarme-magento2-module 1.1.5 -> satisfiable by pagarme/pagarme-magento2-module[1.1.5].

**Comment by mauriciohaygert** [comment]
Boa tarde, este problema foi corrigido na nova release 1.1.6
