### ISSUE TITLE
Validação de endereço do cliente

### ISSUE THREAD

**Issue by josemar-odia** [pagarme/magento2#90]
Tentei configurar de várias maneiras os campos de endereço do cliente:
street[0]
street_0

Tendo verificado corretamente qual o "name" do campos. Mas não passa na validação e/ou não finaliza o pedido.
Magento 2.3.5

Conseguem me dar um caminho do problema?

**Comment by mauricio-tonny** [comment]
@josemar-odia você deve habilitar os 4 campos de endereço na configuração do cliente, e na configuração do PagarMe deixar da seguinte forma:

Parâmetro de rua: street_1
Parâmetro numérico: street_2
Parâmetro de bairro: street_4
Parâmetro de complemento: street_3

Conforme segue no print abaixo:

![Captura de tela de 2022-06-27 14-21-18](https://user-images.githubusercontent.com/68695691/175999150-03d287b6-472e-4b07-bd5e-236c1b5d68fd.png)

Espero ter lhe ajudado.
