### ISSUE TITLE
Deprecated Functionality: strpos(): Passing null to parameter | Magento 2.4.4

### ISSUE THREAD

**Issue by mauricio-tonny** [pagarme/magento2#97]
Ao instalar o módulo, recebo o seguinte retorno na tela de configuração, 

Deprecated Functionality: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /html/vendor/pagarme/pagarme-magento2-module/Gateway/Transaction/Base/Config/Config.php on line 66

Exception in /html/vendor/magento/framework/App/ErrorHandler.php:61

Tela de configuração da forma de pagamento não abre (fica em branco)

Versão do Magento: 2.4.4
Versão do PHP: 7.4.29

Log (debug.log):

[2022-06-27T17:24:11.071011+00:00] main.CRITICAL: Exception: Deprecated Functionality: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /html/vendor/pagarme/pagarme-magento2-module/Gateway/Transaction/Base/Config/Config.php on line 66 in /html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler()
#1 /html/vendor/pagarme/pagarme-magento2-module/Gateway/Transaction/Base/Config/Config.php(66): strpos()
#2 /html/vendor/pagarme/pagarme-magento2-module/Model/Notifications.php(46): Pagarme\Pagarme\Gateway\Transaction\Base\Config\Config->isSandboxMode()

**Comment by redati** [comment]
isso ai é erro do php 8, o modulo ainda não é compatível.

**Comment by RafaMelazzo** [comment]
Boa tarde @mauricio-tonny! Tudo bem?

Está tendo problema com esse erro ainda? Caso precise de suporte, nos envie um e-mail para [opensource@pagar.me](mailto:opensource@pagar.me) com seu site e e-mail de cadastro na Pagar.me, para podermos investigar esse problema e corrigir o Plugin. Entraremos em contato em seguida.

Obrigado!
