### ISSUE TITLE
main.CRITICAL: Warning: Invalid argument supplied for foreach() in Observer/DiscountCyclesObserver.php on line 55 

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#98]
```
Please use the following template to submit your issue. 
Following this template will allow us to quickly investigate and help you with your issue. 
Please be aware that issues which do not conform to this template may be closed. 

DO NOT FORGET TO REMOVE THIS BLOCK
```

### Status

BUG REPORT / TASK

[2022-07-01 12:33:40] main.CRITICAL: Warning: Invalid argument supplied for foreach() in pagarme/pagarme-magento2-module/Observer/DiscountCyclesObserver.php on line 55 {"exception":"[object] (Exception(code: 0): Warning: Invalid argument supplied for foreach() in /pagarme/pagarme-magento2-module/Observer/DiscountCyclesObserver.php on line 55 at vendor/magento/framework/App/ErrorHandler.php:61)"} []

### Checklist

Add checklist if this is a task

- [x] Add slack integration
- [_] Support xyz 

### Steps

1. First step
2. Compra sem descontos. 
3. Second step
4. Third step

### Expected behaviour

How do you think the program should work? Add screenshots and code blocks if necessary.

### Actual behaviour

How does the program work in its current state?

### Environment

Magento versão 2.4.3-p2 - php 7.4

You may write here the specifications like the version of the project, services, operating system, or hardware if applicable.

### Logs / Stack trace

```
Insert your log/stack trace here
```

**Comment by redati** [comment]
ainda acontece em 2.4.5-p1  v 2.0.5

**Comment by samuelmafra** [comment]
Problema persiste na magento 2.4.4-p3 no módulo 2.1.0.

Alguém do suporte consegue ajudar?

**Comment by redati** [comment]
desabilita esse observer Observer/DiscountCyclesObserver.php la em etc/events.xml é so comentar, isso não serve

**Comment by RafaMelazzo** [comment]
Boa tarde @redati e @samuelmafra! Tudo bem?

Estão tendo problema com esse erro ainda? Caso precisem de suporte, nos envie um e-mail para [opensource@pagar.me](mailto:opensource@pagar.me) com seu site e e-mail de cadastro na Pagar.me, para podermos investigar esse problema e corrigir o Plugin. Entraremos em contato em seguida.

Obrigado!

**Comment by redati** [comment]
> Boa tarde @redati e @samuelmafra! Tudo bem?
> 
> Estão tendo problema com esse erro ainda? Caso precisem de suporte, nos envie um e-mail para [opensource@pagar.me](mailto:opensource@pagar.me) com seu site e e-mail de cadastro na Pagar.me, para podermos investigar esse problema e corrigir o Plugin. Entraremos em contato em seguida.
> 
> Obrigado!

Eu mantenho este observador desativado, assim não tenho erros. Poderia ter uma opção no modulo que ativa recursos como esse e subiscrição de planos apenas para pessoas que ativa tal recurso pela configuração do módulo exemplo: "System > Pagame > Config > Ativar Planos". E assim não irá ter erros ou recussos sendo carregados e não usados normalmente pela maioria que usa apenas produtos físicos. Este é o mesmo que https://github.com/pagarme/magento2/issues/152 Agradeço a ateção, eu não posso contribuir mais pois ainda estou estudando, tmj.

**Comment by RafaMelazzo** [comment]
> > Boa tarde @redati e @samuelmafra! Tudo bem?
> > Estão tendo problema com esse erro ainda? Caso precisem de suporte, nos envie um e-mail para [opensource@pagar.me](mailto:opensource@pagar.me) com seu site e e-mail de cadastro na Pagar.me, para podermos investigar esse problema e corrigir o Plugin. Entraremos em contato em seguida.
> > Obrigado!
> 
> Eu mantenho este observador desativado, assim não tenho erros. Poderia ter uma opção no modulo que ativa recursos como esse e subiscrição de planos apenas para pessoas que ativa tal recurso pela configuração do módulo exemplo: "System > Pagame > Config > Ativar Planos". E assim não irá ter erros ou recussos sendo carregados e não usados normalmente pela maioria que usa apenas produtos físicos. Este é o mesmo que #152 Agradeço a ateção, eu não posso contribuir mais pois ainda estou estudando, tmj.

Estamos no momento trabalhando numa refatoração dessa funcionalidade de recorrência. Em breve lançaremos uma atualização que irá resolver esses problemas.

Vou manter a Issue aberta e retorno aqui para avisar quando houver essa atualização.

Obrigado por todos seus relatos! 😄

**Comment by samuelmafra** [comment]
Boa tarde,

Gostaria de acrescentar outro erro que acontece por conta dos observers.

Trabalhamos aqui com um módulo que gera preço customizado do produto através de cálculos avançados, e ao adicionar o produto no carrinho ou atualizar um produto que já está no carrinho, o erro acontece:

[2023-08-18T16:16:30.553956-03:00] main.CRITICAL: Magento\Framework\Exception\NoSuchEntityException: O produto que foi solicitado não existe. Verifique o produto e tente novamente. in /home/account/public_html/magento2/vendor/magento/module-catalog/Model/ProductRepository.php:326
Stack trace:
#0 /home/account/public_html/magento2/vendor/pagarme/pagarme-magento2-module/Block/Product/View/Price/Recurrence.php(175): Magento\Catalog\Model\ProductRepository->getById('194555')
#1 /home/account/public_html/magento2/var/view_preprocessed/pub/static/vendor/pagarme/pagarme-magento2-module/view/frontend/templates/product/price/recurrence.phtml(1): Pagarme\Pagarme\Block\Product\View\Price\Recurrence->getProduct()

Acredito que deveria haver alguma opção de desabilitar esses observers dos serviços do módulo que não são usados.

**Comment by mateus-picoloto** [comment]
Olá @redati, tudo bem?

Essa correção foi lançada na versão 2.2.5.

Muito obrigado!

PSC: @samuelmafra
